title = "kevinpollet.dev"
baseURL = "https://kevinpollet.dev/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
enableRobotsTXT = true
googleAnalytics = "UA-139142142-1"

[params]
  author = "Kevin Pollet"
  images = ["logo.png"]
  gitHubURL = "https://github.com/kevinpollet"
  linkedInURL = "https://linkedin.com/in/kevinpollet"
  twitterURL = "https://twitter.com/@kevinpollet"
