[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"

[[redirects]]
  from = "https://amazing-swanson-8df184.netlify.com/*"
  to = "https://kevinpollet.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none'; object-src 'self'; form-action 'self'; script-src 'self' https://www.google-analytics.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' https://www.google-analytics.com data:;  base-uri 'none'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
