[[redirects]]
  from = "https://inspiring-hermann-b9dd46.netlify.com/*"
  to = "https://kevinpollet.codes/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none'; object-src 'self'; form-action 'self'; script-src 'self' https://www.google-analytics.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' https://www.google-analytics.com data:;  base-uri 'none'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
