[[redirects]]
  from = "https://inspiring-hermann-b9dd46.netlify.com/*"
  to = "https://kevinpollet.codes/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src https: data: 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
